//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA_salon
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Purchase
    {
        public int Id { get; set; }
        [Required]
        public int Id_ser { get; set; }
        [Required]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "Too short name")]
        public string Person { get; set; }
        [Required]
        [RegularExpression(@"^\+[2-9]\d{3}-\d{3}-\d{4}$", ErrorMessage = "Number must have format +xxxx-xxx-xxxx")]
        public string Phone { get; set; }
        [Required]
        public System.DateTime Date { get; set; }
    }
}
