//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA_salon
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Services
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Undefined service")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Too short title")]
        public string Name_ser { get; set; }
        [Required]
        [Range(50, 1000, ErrorMessage = "Too litle price")]
        public int Price { get; set; }
        [Required]
        public System.TimeSpan Time { get; set; }
        [Required]
        public int Id_cat { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
